default_agent: mcp_server
agents:
  weather_agent:
    name: weather_agent
    entrypoint: C:/Users/User1/Downloads/AI For Bharat/workshop5/agentic-ai-with-mcp-and-strands/agentcore/runtime/weather_agentcore.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::891377318455:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-425e274c35
      execution_role_auto_create: false
      account: '891377318455'
      region: us-west-2
      ecr_repository: 891377318455.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-weather_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: weather_agent-hG9v3b97ON
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:891377318455:runtime/weather_agent-hG9v3b97ON
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-weather_agent-builder
      execution_role: arn:aws:iam::891377318455:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-425e274c35
      source_bucket: bedrock-agentcore-codebuild-sources-891377318455-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  mcp_server:
    name: mcp_server
    entrypoint: C:/Users/User1/Downloads/AI For Bharat/workshop5/agentic-ai-with-mcp-and-strands/agentcore/runtime/mcp_server.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\User1\Downloads\AI For Bharat\workshop5\agentic-ai-with-mcp-and-strands\agentcore\runtime
    aws:
      execution_role: arn:aws:iam::891377318455:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-f6e3659767
      execution_role_auto_create: false
      account: '891377318455'
      region: us-west-2
      ecr_repository: 891377318455.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-mcp_server
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: mcp_server-ja2BxlFQZW
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:891377318455:runtime/mcp_server-ja2BxlFQZW
      agent_session_id: ca996dde-a6eb-48ea-8979-2e2174eeda91
    codebuild:
      project_name: bedrock-agentcore-mcp_server-builder
      execution_role: arn:aws:iam::891377318455:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-f6e3659767
      source_bucket: bedrock-agentcore-codebuild-sources-891377318455-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_MjjtqTM3k/.well-known/openid-configuration
        allowedClients:
        - 75dhio0303918ohqet3nk75foh
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
